sequenceDiagram
    autonumber
    participant a3 as mq
    participant a4 as 权益中心
    participant a8 as 飞书
    participant a5 as 发件箱
    participant a6 as 维保服务
    participant a7 as 卡券服务
%% 权益恢复流程
    a3 ->> + a4: 监听首任车主权益恢复消息
    a4 ->> a4: 查询已作废的首任基础权益
    a4 ->> a4: 更新权益、权益明细下发记录状态
    a4 ->> + a5: 将需要恢复的权益数据<br/>保存在发件箱<br/>保存成功后会自动下发一次

%% 维保权益下发
    loop 恢复维保权益<br/>【失败定时任务重试】
        a5 ->>+ a6: 恢复维保权益
        a5 ->> a8: 失败发送飞书提醒【告警群】
    end
%% 卡券权益下发
    loop 恢复卡券权益<br/>【失败定时任务重试】
        a5 ->>+ a7: 恢复卡券权益
        a5 ->> a8: 失败发送飞书提醒【告警群】
    end
    deactivate a4
    deactivate a5

