sequenceDiagram
    autonumber
    participant app as 汽车app
    participant jy as 交易
    participant qy as 权益
    participant fwb as 服务包
    app ->> + fwb: 根据mid查询可购买车辆
    fwb -->> - app: 返回可购买车辆列表
    app -->> app: 选择车辆、服务包
    app ->> + jy: 加购[mid+ssuId+vid]
    jy ->> + qy: 购买资格校验[mid+ssuId+vid]
    qy ->> + fwb: 购买资格校验[mid+ssuId+vid]
    fwb -->> qy: 返回是否有购买权限
    qy -->>- jy: 返回是否有购买权限
    jy -->> - app: 返回结果





