stateDiagram-v2
    [*] --> 用户验证
    用户验证 --> 无购买权限: 无车
    用户验证 --> VID遍历: 有车

    state VID遍历 {
        [*] --> 保单检查
        保单检查 --> vid无购买权限: 无有效保单
        保单检查 --> 补购开关判断: 有保单

        state 补购开关判断 {
            补购关闭 --> 白名单检查
            白名单检查 --> 投保期校验: 不在列
            白名单检查 --> 服务包检查: 在列
            投保期校验 --> vid无购买权限: 不符合
            投保期校验 --> 服务包检查: 符合
            [*] --> 补购开启
            补购开启 --> 服务包检查
        }

        服务包检查 --> vid无购买权限: 已存在
        服务包检查 --> 服务包车型版本检查: 不存在
        服务包车型版本检查 --> vid无购买权限: 不包含
        服务包车型版本检查 --> vid有购买权限: 包含
    }
    vid有购买权限 --> 用户有购买权限
    用户有购买权限 --> [*]
    vid无购买权限 --> [*]