CREATE TABLE `asn_basic`
(
    `id`                     bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `biz_type`               varchar(10)       DEFAULT NULL COMMENT '数据来源类型取自字典表',
    `asn_code`               varchar(200)      DEFAULT NULL COMMENT 'asn',
    `receive_warehouse_code` varchar(200)      DEFAULT NULL COMMENT '收货仓库代码',
    `state`                  varchar(20)       DEFAULT NULL COMMENT '状态：n1:已发货 ',
    `delivery_time`          datetime          DEFAULT NULL COMMENT '发货时间',
    `est_arrival_time`       datetime          DEFAULT NULL COMMENT '预计发货时间',
    `suppier_sap_code`       varchar(200)      DEFAULT NULL COMMENT '供应商sap代码',
    `description`            varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`                 varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`                 bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`            char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`            char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `recv_sync_status`       varchar(32)       DEFAULT NULL COMMENT '收货同步状态',
    `recv_sync_result`       varchar(255)      DEFAULT NULL COMMENT '收货同步结果',
    `asn_source`             varchar(32)       DEFAULT NULL COMMENT '数据来源',
    `asn_sync_status`        bigint(20) DEFAULT '0' COMMENT '三方接口同步状态，非0表示失败0表示成功',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `unq_asn_code` (`asn_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8680 DEFAULT CHARSET=utf8mb4 COMMENT='预发货单基础信息';
CREATE TABLE `asn_deliver_info`
(
    `id`                    bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `biz_type`              varchar(10)       DEFAULT NULL COMMENT '数据来源类型取自字典表',
    `asn_code`              varchar(32)       DEFAULT NULL COMMENT 'asn号码',
    `asn_line_no`           varchar(32)       DEFAULT NULL COMMENT 'asn行号',
    `plan_line_no`          varchar(32)       DEFAULT NULL COMMENT '计划行号',
    `srm_contract_no`       varchar(32)       DEFAULT NULL COMMENT '框架协议号',
    `contract_line_no`      varchar(32)       DEFAULT NULL COMMENT '框架协议行号',
    `sale_part_num`         varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `delivery_qty`          int(11) unsigned DEFAULT NULL COMMENT '发货数量',
    `unit`                  varchar(20)       DEFAULT NULL COMMENT '订单单位',
    `standard_pack_qty`     decimal(20, 3) unsigned DEFAULT NULL COMMENT '标准装箱数量',
    `last_received_time`    datetime          DEFAULT NULL COMMENT '最后收货时间',
    `batch_no`              varchar(20)       DEFAULT NULL COMMENT '批次号',
    `product_time`          datetime          DEFAULT NULL COMMENT '生产日期',
    `expire_time`           datetime          DEFAULT NULL COMMENT '有效日期止',
    `description`           varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`                varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`                bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`           char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`           datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`           char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`           datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `material_number`       varchar(64)       DEFAULT NULL COMMENT '备件号码',
    `plant_code`            varchar(64)       DEFAULT NULL COMMENT '工厂代码',
    `storage_location_code` varchar(64)       DEFAULT NULL COMMENT '库存地点代码',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `idx_delever` (`asn_code`,`sale_part_num`)
) ENGINE=InnoDB AUTO_INCREMENT=9299 DEFAULT CHARSET=utf8mb4 COMMENT='发货信息表';
CREATE TABLE `asn_pack_info`
(
    `id`                bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `biz_type`          varchar(10)       DEFAULT NULL COMMENT '数据来源类型取自字典表',
    `asn_code`          varchar(32)       DEFAULT NULL COMMENT 'asn_code',
    `serial_no`         varchar(16)       DEFAULT NULL COMMENT '序号',
    `sale_part_num`     varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `pack_no`           varchar(64)       DEFAULT NULL COMMENT '箱标签号',
    `standard_pack_qty` decimal(20, 3) unsigned DEFAULT NULL COMMENT '标准装箱数量',
    `actual_pack_qty`   decimal(20, 3) unsigned DEFAULT NULL COMMENT '实际装箱数量',
    `description`       varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`            varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`            bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`       char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`       char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=457 DEFAULT CHARSET=utf8mb4 COMMENT='包装信息表';
CREATE TABLE `asn_receive_info`
(
    `id`                 bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `biz_type`           varchar(10)       DEFAULT NULL COMMENT '数据来源类型取自字典表',
    `asn_code`           varchar(32)       DEFAULT NULL COMMENT 'asn号码',
    `asn_line_no`        varchar(32)       DEFAULT NULL COMMENT 'asn行号',
    `sale_part_num`      varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `received_qty`       int(11) unsigned DEFAULT NULL COMMENT '收获数量',
    `received_time`      datetime          DEFAULT NULL COMMENT '收货时间',
    `broken_quantity`    int(11) DEFAULT '0' COMMENT '货损数量',
    `incorrect_quantity` int(11) DEFAULT '0' COMMENT '货错数量',
    `description`        varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`             varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`             bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`        char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`        char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `idx_unique` (`asn_code`,`biz_type`,`sale_part_num`)
) ENGINE=InnoDB AUTO_INCREMENT=1243 DEFAULT CHARSET=utf8mb4 COMMENT='外部系统收货信息';

CREATE TABLE `order_calendar`
(
    `id`                    bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `store_code`            varchar(100) NOT NULL COMMENT '门店code',
    `order_cycle_type`      int(11) NOT NULL DEFAULT '0' COMMENT '订单周期类型 0-按周  1-按月',
    `order_cycle`           varchar(100)          DEFAULT NULL COMMENT '订单周期',
    `store_report_deadline` time                  DEFAULT NULL COMMENT '门店上报截至时间',
    `transfer_time`         time                  DEFAULT NULL COMMENT '转单时间1',
    `transfer_time_2`       time                  DEFAULT NULL COMMENT '转单时间2',
    `remark`                varchar(1024)         DEFAULT NULL COMMENT '备注',
    `is_del`                bit(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`           char(32)              DEFAULT NULL COMMENT '创建者',
    `create_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`           char(32)              DEFAULT NULL COMMENT '更新者',
    `update_time`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `biz_type`              varchar(10)           DEFAULT NULL COMMENT '业务类型数据来源类型取自字典表',
    `description`           varchar(1024)         DEFAULT NULL COMMENT '描述',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8 COMMENT='訂單日曆表';

CREATE TABLE `order_plan`
(
    `id`                     bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `biz_type`               varchar(16)       DEFAULT NULL COMMENT '业务类型',
    `order_plan_no`          varchar(32)       DEFAULT NULL COMMENT '计划行号',
    `contract_no`            varchar(32)       DEFAULT NULL COMMENT '框架协议号',
    `company_code`           varchar(32)       DEFAULT NULL COMMENT '公司代码',
    `supplier_sap_code`      varchar(32)       DEFAULT NULL COMMENT '供应商编码',
    `receive_warehouse_code` varchar(32)       DEFAULT NULL COMMENT '收货仓库代码',
    `priority`               varchar(32)       DEFAULT NULL COMMENT '优先级',
    `sale_part_num`          varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `quantity`               int(11) DEFAULT '0' COMMENT '数量',
    `delivery_qty`           int(11) DEFAULT '0' COMMENT '已发货数量',
    `received_qty`           int(11) DEFAULT '0' COMMENT '已收货数量',
    `order_unit`             varchar(64)       DEFAULT NULL COMMENT '订货单位',
    `plan_status`            varchar(32)       DEFAULT NULL COMMENT '状态',
    `est_arrival_time`       datetime          DEFAULT NULL COMMENT '预计到货时间',
    `audit_user`             varchar(64)       DEFAULT NULL COMMENT '审核人',
    `audit_time`             datetime          DEFAULT NULL COMMENT '审核时间',
    `plant_code`             varchar(64)       DEFAULT NULL COMMENT '工厂代码',
    `sync_status`            varchar(32)       DEFAULT NULL COMMENT '同步状态',
    `version`                int(11) NOT NULL DEFAULT '1' COMMENT '版本',
    `description`            varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`                 varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`                 bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`            char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`            char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                      `idx_spn_cn_bt` (`sale_part_num`,`contract_no`,`biz_type`),
    KEY                      `idx_opn_bt` (`order_plan_no`,`biz_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1206 DEFAULT CHARSET=utf8mb4 COMMENT='要货计划';
CREATE TABLE `order_plan_operate_log`
(
    `id`            bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `order_plan_id` bigint(20) unsigned NOT NULL COMMENT '要货计划id',
    `action_desc`   varchar(32)       DEFAULT NULL COMMENT '操作描述',
    `modify_column` varchar(32)       DEFAULT NULL COMMENT '修改字段',
    `old_value`     varchar(32)       DEFAULT NULL COMMENT '原始值',
    `new_value`     varchar(32)       DEFAULT NULL COMMENT '修改值',
    `description`   varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`        varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`        bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`   char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`   char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY             `idx_opi` (`order_plan_id`)
) ENGINE=InnoDB AUTO_INCREMENT=535 DEFAULT CHARSET=utf8mb4 COMMENT='要货计划修改记录';

CREATE TABLE `pallet`
(
    `id`               bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `pallet_code`      varchar(200) CHARACTER SET utf8 NOT NULL COMMENT '托盘编码',
    `pallet_length`    int(11) DEFAULT NULL COMMENT '长(mm)',
    `pallet_width`     int(11) DEFAULT NULL COMMENT '宽(mm)',
    `pallet_height`    int(11) DEFAULT NULL COMMENT '高(mm)',
    `pallet_type`      varchar(50) CHARACTER SET utf8  NOT NULL COMMENT '托盘类型数据来源类型取自字典表',
    `status`           bit(1)                          NOT NULL DEFAULT b'1' COMMENT '是否启用 1是 0否 默认1',
    `biz_type`         varchar(10) CHARACTER SET utf8  NOT NULL COMMENT '业务类型数据来源类型取自字典表',
    `description`      varchar(1024) CHARACTER SET utf8         DEFAULT NULL COMMENT '描述',
    `remark`           varchar(1024) CHARACTER SET utf8         DEFAULT NULL COMMENT '备注',
    `is_del`           bit(1)                          NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`      char(32) CHARACTER SET utf8              DEFAULT NULL COMMENT '创建者',
    `create_time`      datetime                        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`      char(32) CHARACTER SET utf8              DEFAULT NULL COMMENT '更新者',
    `update_time`      datetime                        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version`          int(11) DEFAULT '0' COMMENT '版本号',
    `num`              int(11) NOT NULL DEFAULT '1' COMMENT '数量为正整型',
    `pallet_item_name` varchar(20)                     NOT NULL COMMENT '托盘类型名称',
    PRIMARY KEY (`id`),
    KEY                `idx_code` (`pallet_code`,`biz_type`)
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=utf8mb4 COMMENT='托盘主数据';

CREATE TABLE `purchase_forecast`
(
    `id`                 bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `biz_type`           varchar(20) NOT NULL,
    `company_code`       varchar(50)          DEFAULT NULL COMMENT '公司代码',
    `factory_code`       varchar(50)          DEFAULT NULL COMMENT '工厂代码',
    `supplier_code`      varchar(45)          DEFAULT NULL COMMENT '供应商代码',
    `sale_part_number`   varchar(45)          DEFAULT NULL COMMENT '售后件号',
    `n1`                 int(11) DEFAULT NULL COMMENT '开始月份+1的预测值',
    `n2`                 int(11) DEFAULT NULL COMMENT '开始月份+2的预测值',
    `n3`                 int(11) DEFAULT NULL COMMENT '开始月份+3的预测值',
    `n4`                 int(11) DEFAULT NULL COMMENT '开始月份+4的预测值',
    `n5`                 int(11) DEFAULT NULL COMMENT '开始月份+5的预测值',
    `n6`                 int(11) DEFAULT NULL COMMENT '开始月份+6的预测值',
    `n7`                 int(11) DEFAULT NULL COMMENT '开始月份+7的预测值',
    `n8`                 int(11) DEFAULT NULL COMMENT '开始月份+8的预测值',
    `n9`                 int(11) DEFAULT NULL COMMENT '开始月份+9的预测值',
    `n10`                int(11) DEFAULT NULL COMMENT '开始月份+10的预测值',
    `n11`                int(11) DEFAULT NULL COMMENT '开始月份+11的预测值',
    `n12`                int(11) DEFAULT NULL COMMENT '开始月份+12的预测值',
    `n13`                int(11) DEFAULT NULL COMMENT '开始月份+13的预测值',
    `n14`                int(11) DEFAULT NULL COMMENT '开始月份+14的预测值',
    `n15`                int(11) DEFAULT NULL COMMENT '开始月份+15的预测值',
    `n16`                int(11) DEFAULT NULL COMMENT '开始月份+16的预测值',
    `n17`                int(11) DEFAULT NULL COMMENT '开始月份+17的预测值',
    `n18`                int(11) DEFAULT NULL COMMENT '开始月份+18的预测值',
    `issued_user`        varchar(45)          DEFAULT NULL COMMENT '下发人',
    `issued_time`        datetime             DEFAULT NULL COMMENT '下发时间',
    `issued_status`      varchar(15)          DEFAULT 'wait_issued' COMMENT '下发状态',
    `issued_status_desc` varchar(500)         DEFAULT NULL COMMENT '下发状态描述',
    `description`        varchar(1024)        DEFAULT NULL COMMENT '描述',
    `remark`             varchar(1024)        DEFAULT NULL COMMENT '备注',
    `is_del`             bit(1)      NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`        char(32)             DEFAULT NULL COMMENT '创建者',
    `create_time`        datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`        char(32)             DEFAULT NULL COMMENT '更新者',
    `update_time`        datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY                  `idx_supplier_code` (`supplier_code`,`biz_type`),
    KEY                  `idx_sale_part_num` (`sale_part_number`,`biz_type`),
    KEY                  `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1045 DEFAULT CHARSET=utf8mb4 COMMENT='采购预测';
CREATE TABLE `sale_price`
(
    `id`                   bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `biz_type`             varchar(16)       DEFAULT NULL COMMENT '业务类型',
    `sale_part_num`        varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `material_number`      varchar(64)       DEFAULT NULL COMMENT '备件号码',
    `price_type`           varchar(32)       DEFAULT NULL COMMENT '价格类型',
    `price_before_vat`     decimal(20, 2)    DEFAULT NULL COMMENT '价格（不含税）',
    `price_after_vat`      decimal(20, 2)    DEFAULT NULL COMMENT '价格（含税）',
    `effective_start_time` datetime          DEFAULT NULL COMMENT '有效开始日期',
    `del_unique_key`       bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '唯一索引，删除后用Id赋值',
    `description`          varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`               varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`               bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`          char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`          char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_spn_est_pt_bt_duk` (`sale_part_num`,`effective_start_time`,`price_type`,`biz_type`,`del_unique_key`),
    KEY                    `idx_ut_bt` (`update_time`,`biz_type`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COMMENT='销售价格';

CREATE TABLE `sale_price_approval`
(
    `id`                  bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `biz_type`            varchar(16)       DEFAULT NULL COMMENT '业务类型',
    `approval_no`         varchar(32)       DEFAULT NULL COMMENT '审批单号',
    `proc_inst_id`        varchar(64)       DEFAULT NULL COMMENT '当前流程实例id',
    `detail_quantity`     int(11) DEFAULT '0' COMMENT '明细数量',
    `attachment_quantity` int(11) DEFAULT '0' COMMENT '附件数量',
    `approval_status`     varchar(32)       DEFAULT NULL COMMENT '审核状态',
    `description`         varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`              varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`              bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`         char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`         char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COMMENT='销售价格审批';

CREATE TABLE `sale_price_approval_attachment`
(
    `id`          bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `biz_type`    varchar(16)                     DEFAULT NULL COMMENT '业务类型',
    `approval_id` bigint(20) unsigned NOT NULL COMMENT '销售价格审批id',
    `file_name`   varchar(64)                     DEFAULT NULL COMMENT '文件名',
    `file_url`    varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '文件链接',
    `description` varchar(1024)                   DEFAULT NULL COMMENT '描述',
    `remark`      varchar(1024)                   DEFAULT NULL COMMENT '备注',
    `is_del`      bit(1)   NOT NULL               DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user` char(32)                        DEFAULT NULL COMMENT '创建者',
    `create_time` datetime NOT NULL               DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user` char(32)                        DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL               DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY           `uk_aid_bt` (`approval_id`,`biz_type`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=utf8mb4 COMMENT='销售价格审批附件';
CREATE TABLE `sale_price_approval_detail`
(
    `id`                   bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `biz_type`             varchar(16)       DEFAULT NULL COMMENT '业务类型',
    `approval_id`          bigint(20) unsigned NOT NULL COMMENT '销售价格审批id',
    `sale_part_num`        varchar(64)       DEFAULT NULL COMMENT '售后件号',
    `material_number`      varchar(64)       DEFAULT NULL COMMENT '备件号码',
    `price_type`           varchar(32)       DEFAULT NULL COMMENT '价格类型',
    `price_before_vat`     decimal(20, 2)    DEFAULT NULL COMMENT '价格（不含税）',
    `price_after_vat`      decimal(20, 2)    DEFAULT NULL COMMENT '价格（含税）',
    `effective_start_time` datetime          DEFAULT NULL COMMENT '有效开始日期',
    `del_unique_key`       bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '唯一索引，删除后用Id赋值',
    `description`          varchar(1024)     DEFAULT NULL COMMENT '描述',
    `remark`               varchar(1024)     DEFAULT NULL COMMENT '备注',
    `is_del`               bit(1)   NOT NULL DEFAULT b'0' COMMENT '是否删除 1是 0否 默认0',
    `create_user`          char(32)          DEFAULT NULL COMMENT '创建者',
    `create_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user`          char(32)          DEFAULT NULL COMMENT '更新者',
    `update_time`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_aid_spn_est_pt_bt_duk` (`approval_id`,`sale_part_num`,`effective_start_time`,`price_type`,`biz_type`,`del_unique_key`)
) ENGINE=InnoDB AUTO_INCREMENT=22726 DEFAULT CHARSET=utf8mb4 COMMENT='销售价格审批价格明细'